services:
  db:
    image: postgres:13.2-alpine
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./database:/var/lib/postgresql/data

  backend:
    image: backend-project
    container_name: backend
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    depends_on:
      - db

  frontend:
    image: frontend-project
    container_name: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api
    depends_on:
      - backend

  redis:
    image: redis:latest
    restart: unless-stopped

  proxy:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
