services:
  backend:
    image: backend-project
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
  frontend:
    image: frontend-project
    container_name: frontend
    ports:
      - 5000:5000
  redis:
    image: redis:latest
    restart: unless-stopped
