services:
  db:
    image: postgres:13.2-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
  backend:
    image: backend-project
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    depends_on:
      - db
  frontend:
    image: frontend-project
    container_name: frontend
    ports:
      - 5000:5000
  redis:
    image: redis:latest
    restart: unless-stopped
