FROM node:14

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN <<EOF
npm install
npm run build
npm install -g serve
useradd -m appuser
rm -rf /var/lib/apt/lists/*
EOF

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]
